version: '3.8'

services:

  maintenance:
    build:
      context: ./docker
      dockerfile: maintenance.dockerfile
    restart: always
    volumes:
      - ./docker/volumes/maintenance/certbot:/var/certbot/
      - ./docker/volumes/maintenance/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - nginx

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/volumes/wordpress/data:/var/www/html
      - ./docker/volumes/webmail/html/:/var/www/webmail
      - ./docker/volumes/maintenance/certbot:/var/certbot/
      - ./docker/volumes/maintenance/letsencrypt/:/etc/nginx/ssl/
    depends_on:
      - strapi
      - wordpress

  wordpress:
    build:
      context: ./docker
      dockerfile: wordpress.dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: general
      WORDPRESS_DB_PASSWORD: Password#01
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./docker/volumes/wordpress/data:/var/www/html
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker
      dockerfile: mysql.dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password#01
      MYSQL_DATABASE: general
      MYSQL_USER: general
      MYSQL_PASSWORD: Password#01
    volumes:
      - ./docker/config/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql/data:/var/lib/mysql

  strapi:
    build:
      context: ./docker
      dockerfile: strapi.dockerfile
    restart: always
    ports:
      - 1337:1337
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: secret
    volumes:
      - ./docker/volumes/strapi/app:/srv/app
    depends_on:
      - mongo

  mongo:
    build:
      context: ./docker
      dockerfile: mongo.dockerfile
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./docker/volumes/mongo/data:/data/db

  mailserver:
    build:
      context: ./docker
      dockerfile: mailserver.dockerfile
    restart: always
    hostname: mail
    domainname: example.com
    env_file: ./docker/config/mailserver/mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker/volumes/mailserver/mail-data/:/var/mail/
      - ./docker/volumes/mailserver/mail-state/:/var/mail-state/
      - ./docker/volumes/mailserver/mail-logs/:/var/log/mail/
      - ./docker/volumes/mailserver/config/:/tmp/docker-mailserver/
      - ./docker/volumes/maintenance/letsencrypt/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
